### ISSUE TITLE
Running SoundClass on MacBook Pro M1 Pro...Not working

### ISSUE THREAD

**Issue by jrevueltaa** [bmsasilva/soundClass#5]
Hello,

I'm currently putting up the example on your paper title: "soundClass: An automatic sound classification tool for biodiversity monitoring using machine learning". I'm using a MacBook Pro M1 Pro and I got the following problem while trying to run it. I did run it on a Windows Computer with no GPU and it worked. However, I'd like to take advantage of the GPU available in my hardware. After running the Epoch 1/20, I got the following error (attached figure). Could you help me out?

<img width="1512" alt="Screen Shot 2022-09-12 at 18 53 17" src="https://user-images.githubusercontent.com/58447718/189772249-572bcb3d-fa73-4640-bf4b-67ef3130d976.png">

<img width="1512" alt="Screen Shot 2022-09-12 at 18 51 58" src="https://user-images.githubusercontent.com/58447718/189772243-1b867ab5-b507-4aa3-9fb4-0aa0ad8389e8.png">

**Comment by bmsasilva** [comment]
Hi,
from what I can see from the screenshot, the error is caused by a python segfault (i.e. a program is trying to read or write an illegal memory location). This error is most certainly related with the usage of the GPU by keras and unfortunately we cannot help you with this issue. Nevertheless, going directly to keras (https://github.com/keras-team/keras/issues) is probably the best way to find help on this issue.
Regards

**Comment by jrevueltaa** [comment]
Thanks @bmsasilva. I'll keep working on the issue. Let you know how it solve it when it happens.

@jrevueltaa

**Comment by bmsasilva** [comment]
Further discussion about this issue:
https://stackoverflow.com/questions/73682439/r-error-while-using-soundclass-package-and-tensor-flow-on-apple-silicon-m1-pro
